server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://123.60.37.212:3306/gcj_zgb_test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: part
    password: 09a3vM#gPi41tGuY
    driver-class-name: com.mysql.cj.jdbc.Driver

#整合mybatis
mybatis:
  type-aliases-package: com.example.springbootmybatis.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
